// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/nymtech/nym-directory/models"
	mock "github.com/stretchr/testify/mock"
)

// IDb is an autogenerated mock type for the IDb type
type IDb struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *IDb) Add(_a0 models.PersistedMixStatus) {
	_m.Called(_a0)
}

// List provides a mock function with given fields: pubkey, limit
func (_m *IDb) List(pubkey string, limit int) []models.PersistedMixStatus {
	ret := _m.Called(pubkey, limit)

	var r0 []models.PersistedMixStatus
	if rf, ok := ret.Get(0).(func(string, int) []models.PersistedMixStatus); ok {
		r0 = rf(pubkey, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PersistedMixStatus)
		}
	}

	return r0
}
