package main

import (
	"github.com/nymtech/directory-server/rest"
	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

func main() {
	cfg := &rest.Config{
		Addr: "",
		Port: 8080,
	}

	server := rest.New(cfg)

	server.Run()

	wait := make(chan struct{})
	<-wait
	// r := gin.New()

	// url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	// r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	// r.Run()
}
