package main

import (
	"github.com/nymtech/directory-server/rest"
	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

func main() {
	cfg := &rest.Config{
		Addr: "",
		Port: 8080,
	}

	server := rest.New(cfg)

	server.Run()

	wait := make(chan struct{})
	<-wait
}
