// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/nymtech/directory-server/models"

// Db is an autogenerated mock type for the Db type
type Db struct {
	mock.Mock
}

// AddCoco provides a mock function with given fields: _a0
func (_m *Db) AddCoco(_a0 models.Presence) {
	_m.Called(_a0)
}

// AddMix provides a mock function with given fields: _a0
func (_m *Db) AddMix(_a0 models.MixNodePresence) {
	_m.Called(_a0)
}

// Topology provides a mock function with given fields:
func (_m *Db) Topology() models.Topology {
	ret := _m.Called()

	var r0 models.Topology
	if rf, ok := ret.Get(0).(func() models.Topology); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Topology)
	}

	return r0
}
