// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/nymtech/directory-server/models"

// Db is an autogenerated mock type for the Db type
type Db struct {
	mock.Mock
}

// AddMix provides a mock function with given fields: _a0
func (_m *Db) AddMix(_a0 models.MixNodePresence) {
	_m.Called(_a0)
}

// List provides a mock function with given fields:
func (_m *Db) List() map[string]models.MixNodePresence {
	ret := _m.Called()

	var r0 map[string]models.MixNodePresence
	if rf, ok := ret.Get(0).(func() map[string]models.MixNodePresence); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]models.MixNodePresence)
		}
	}

	return r0
}
