// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/nymtech/nym-directory/models"
	mock "github.com/stretchr/testify/mock"
)

// IService is an autogenerated mock type for the IService type
type IService struct {
	mock.Mock
}

// CreateMixStatus provides a mock function with given fields: metric
func (_m *IService) CreateMixStatus(metric models.MixStatus) {
	_m.Called(metric)
}

// List provides a mock function with given fields:
func (_m *IService) List() []models.PersistedMixStatus {
	ret := _m.Called()

	var r0 []models.PersistedMixStatus
	if rf, ok := ret.Get(0).(func() []models.PersistedMixStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PersistedMixStatus)
		}
	}

	return r0
}
