// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-06-03 13:27:15.377195976 +0100 BST m=+0.059049760

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a temporarily centralized directory/PKI/metrics API to allow us to get the other Nym node types running. Its functionality will eventually be folded into other parts of Nym.",
        "title": "Nym Directory API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "https://github.com/nymtech/nym-directory/license"
        },
        "version": "0.0.4"
    },
    "paths": {
        "/api/healthcheck": {
            "get": {
                "description": "Returns a 200 if the directory server is available. Good route to use for automated monitoring.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "Lets the directory server tell the world it's alive.",
                "operationId": "healthCheck",
                "responses": {
                    "200": {}
                }
            }
        },
        "/api/metrics/mixes": {
            "get": {
                "description": "For demo and debug purposes it gives us the ability to generate useful visualisations of network traffic.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Lists mixnode activity in the past 3 seconds",
                "operationId": "listMixMetrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MixMetric"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "For demo and debug purposes it gives us the ability to generate useful visualisations of network traffic.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Create a metric detailing how many messages a given mixnode sent and received",
                "operationId": "createMixMetric",
                "parameters": [
                    {
                        "description": "object",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.MixMetric"
                        }
                    }
                ],
                "responses": {
                    "201": {},
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/api/presence/coconodes": {
            "post": {
                "description": "Nym Coconut nodes can ping this method to let the directory server know they're up. We can then use this info to create topologies of the overall Nym network.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "presence"
                ],
                "summary": "Lets a coconut node tell the directory server it's alive",
                "operationId": "addCocoNode",
                "parameters": [
                    {
                        "description": "object",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.CocoHostInfo"
                        }
                    }
                ],
                "responses": {
                    "201": {},
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/api/presence/disallow": {
            "post": {
                "description": "Sometimes when a node isn't working we need to temporarily remove it from use so that it doesn't mess up QoS for the whole network.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "presence"
                ],
                "summary": "Takes a node out of the regular topology and puts it in the disallowed nodes list",
                "operationId": "disallow",
                "parameters": [
                    {
                        "description": "object",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Disallow"
                        }
                    }
                ],
                "responses": {
                    "201": {},
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/api/presence/gateways": {
            "post": {
                "description": "Nym mix gateways can ping this method to let the directory server know they're up. We can then use this info to create topologies of the overall Nym network.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "presence"
                ],
                "summary": "Lets a gateway tell the directory server it's alive",
                "operationId": "addGateway",
                "parameters": [
                    {
                        "description": "object",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.GatewayHostInfo"
                        }
                    }
                ],
                "responses": {
                    "201": {},
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/api/presence/mixnodes": {
            "post": {
                "description": "Nym mixnodes can ping this method to let the directory server know they're up. We can then use this info to create topologies of the overall Nym network.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "presence"
                ],
                "summary": "Lets mixnode a node tell the directory server it's alive",
                "operationId": "addMixNode",
                "parameters": [
                    {
                        "description": "object",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.MixHostInfo"
                        }
                    }
                ],
                "responses": {
                    "201": {},
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/api/presence/mixproviders": {
            "post": {
                "description": "Nym mix providers can ping this method to let the directory server know they're up. We can then use this info to create topologies of the overall Nym network.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "presence"
                ],
                "summary": "Lets a mixnode tell the directory server it's alive",
                "operationId": "addMixProvider",
                "parameters": [
                    {
                        "description": "object",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.MixProviderHostInfo"
                        }
                    }
                ],
                "responses": {
                    "201": {},
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/api/presence/topology": {
            "get": {
                "description": "Nym nodes periodically ping the directory server to register that they're alive. This method provides a list of nodes which have been most recently seen.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "presence"
                ],
                "summary": "Lists which Nym mixnodes, providers, gateways, and coconodes are alive",
                "operationId": "topology",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Topology"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CocoHostInfo": {
            "type": "object",
            "required": [
                "pubKey",
                "version",
                "type"
            ],
            "properties": {
                "host": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "pubKey": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.CocoPresence": {
            "type": "object",
            "required": [
                "lastSeen",
                "pubKey",
                "version",
                "type"
            ],
            "properties": {
                "host": {
                    "type": "string"
                },
                "lastSeen": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "pubKey": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.Disallow": {
            "type": "object",
            "properties": {
                "hostKey": {
                    "type": "string"
                }
            }
        },
        "models.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.GatewayHostInfo": {
            "type": "object",
            "required": [
                "pubKey",
                "version"
            ],
            "properties": {
                "clientListener": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "mixnetListener": {
                    "type": "string"
                },
                "pubKey": {
                    "type": "string"
                },
                "registeredClients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RegisteredClient"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.GatewayPresence": {
            "type": "object",
            "required": [
                "lastSeen",
                "pubKey",
                "version"
            ],
            "properties": {
                "clientListener": {
                    "type": "string"
                },
                "lastSeen": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "mixnetListener": {
                    "type": "string"
                },
                "pubKey": {
                    "type": "string"
                },
                "registeredClients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RegisteredClient"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.MixHostInfo": {
            "type": "object",
            "required": [
                "version",
                "layer",
                "pubKey"
            ],
            "properties": {
                "host": {
                    "type": "string"
                },
                "layer": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "pubKey": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.MixMetric": {
            "type": "object",
            "required": [
                "received",
                "pubKey"
            ],
            "properties": {
                "pubKey": {
                    "type": "string"
                },
                "received": {
                    "type": "integer"
                },
                "sent": {
                    "type": "object",
                    "required": [
                        "sent"
                    ]
                }
            }
        },
        "models.MixNodePresence": {
            "type": "object",
            "required": [
                "pubKey",
                "version",
                "layer",
                "lastSeen"
            ],
            "properties": {
                "host": {
                    "type": "string"
                },
                "lastSeen": {
                    "type": "integer"
                },
                "layer": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "pubKey": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.MixProviderHostInfo": {
            "type": "object",
            "required": [
                "version",
                "pubKey"
            ],
            "properties": {
                "clientListener": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "mixnetListener": {
                    "type": "string"
                },
                "pubKey": {
                    "type": "string"
                },
                "registeredClients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RegisteredClient"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.MixProviderPresence": {
            "type": "object",
            "required": [
                "lastSeen",
                "pubKey",
                "version"
            ],
            "properties": {
                "clientListener": {
                    "type": "string"
                },
                "lastSeen": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "mixnetListener": {
                    "type": "string"
                },
                "pubKey": {
                    "type": "string"
                },
                "registeredClients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RegisteredClient"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.RegisteredClient": {
            "type": "object",
            "required": [
                "pubKey"
            ],
            "properties": {
                "pubKey": {
                    "type": "string"
                }
            }
        },
        "models.Topology": {
            "type": "object",
            "properties": {
                "cocoNodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CocoPresence"
                    }
                },
                "disallowed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MixNodePresence"
                    }
                },
                "gatewayNodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GatewayPresence"
                    }
                },
                "mixNodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MixNodePresence"
                    }
                },
                "mixProviderNodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MixProviderPresence"
                    }
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
